### ISSUE TITLE
Coconut, Rum, Bombs are not interactable

### ISSUE THREAD

**Issue by Josh9309** [Josh9309/Blackbeard#4]
You can't use the coconut, Rum, bombs. They will not interact with the parrot.

**Comment by Josh9309** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parrot pickup Bug](https://trello.com/c/p8DMA2Z5/60-parrot-pickup-bug)

**Comment by k-idzik** [comment]
Items can now be picked up, since item pickup was tied to item scale this created some instances where the pickup point was too high above the item. This is remedied for all items by getting the size of the collider on the object.
